name: marvel
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  json_annotation: ^4.5.0
  retrofit: ^3.0.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.3
  json_serializable: ^6.1.5
  retrofit_generator: ^4.0.1

flutter_icons:
  android: "launch_icon"
  ios: true
  image_path: "assets/images/launch_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/placeholder.png
